### ISSUE TITLE
.gitlab-ci.yml caching broken

### ISSUE THREAD

**Issue by masaeedu** [input-output-hk/rscoin-haskell#4]
I was imitating your `.gitlab-ci.yml` for building a large haskell project with caching, and found some bugs. Your `ln -s ___restored /root/.stack` is backwards; you're creating a symlink in `/root/.stack/___restored`, which stack will never use. Even if you flip this around, the Gitlab runner's caching doesn't seem to follow symlinks, and at the very least won't restore the symlink target directory correctly.

After tweaking it a bit, I ended up with this `.gitlab-ci.yml`, which works correctly for us (committing twice with no changes to the Haskell code results in `stack build` being a non-op):

```yml
# ...

build:
  cache:
    untracked: true
    paths:
      - server/.stack-work
      - server/___restore
  script:
    - cd server
    - mkdir -p `pwd`/___restore
    - test -d `pwd`/___restore/.stack && rm -rf /root/.stack && cp -r `pwd`/___restore/.stack /root
    - stack build
    - cp -rf /root/.stack `pwd`/___restore
```

One could probably make this both simpler and more efficient if rsync was added to the container, but we're using the haskell image directly.
